[package]
name = "sdformat"
version = "0.1.0"
edition = "2018"

[dependencies]
# cxx = "1.0"
serde-xml-rs = "0.5"
serde = { version = "1", features = ["derive"]}

[dev-dependencies]
pretty_assertions = "0.7"